# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_binary_packages:
  - r-cran-stringi
  - r-cran-knitr
  - r-cran-testthat
  - r-cran-dplyr
  - r-cran-purrr
  - r-cran-tidyr
