# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      r: oldrel
      name: linux-old
      before_script: Rscript -e "remotes::install_github('tidyverse/tidyr')"
    - os: linux
      r: release
      name: linux-release
    - os: linux
      r: devel
      name: linux-devel
      before_script: Rscript -e "remotes::install_github('tidyverse/tidyr')"
    - os: linux
      r: release
      name: tidyr-devel
      before_script: Rscript -e "remotes::install_github('tidyverse/tidyr')"
